version: '3.7'

services:
  nestjs-demo-db:
    container_name: nestjs-demo-db
    image: postgres
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nestjs-demo-db'
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - ./pgdata:/var/ib/postgresql/data
