version: '3.7'

services:
  nestjs-demo-db:
    container_name: nestjs-demo-db
    image: postgres
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nestjs-demo-db'
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - ./pgdata:/var/ib/postgresql/data

  app:
    container_name: nestjs-demo
    image: nestjs-demo:latest
    environment:
      PP_PORT: 3000
      DB_PORT: 5435
      DB_HOST: nestjs-demo-db
      DB_DATABASE: 'nestjs-demo-db'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      SECRET_KEY: test
    ports:
      - '3000:3000'
    depends_on:
      - nestjs-demo-db
